### ISSUE TITLE
Could not find member 'CGColor'

### ISSUE THREAD

**Issue by datomnurdin** [yeahdongcn/UIColor-Hex-Swift#10]
I install this library via cocoapod but I got this error message

```
Could not find member 'CGColor'
```

Please advice. Thank you.

**Comment by yeahdongcn** [comment]
Could you forward me the complete error message?

**Comment by datomnurdin** [comment]
this is only the complete error message.

**Comment by yeahdongcn** [comment]
Error occurred on installing or compiling? 
What's your Xcode version?

**Comment by datomnurdin** [comment]
compiling. No issue with installing. my xcode version, 6.3.1.

**Comment by yeahdongcn** [comment]
Give me some time I will try this after launch.

**Comment by yeahdongcn** [comment]
Hello, I created a project and there is no error while compiling. Could you send your project to me then I can identify what the problem is?
BTW, I've updated the source for a little bit.

**Comment by yeahdongcn** [comment]
I've mailed you my project, please take a look.
