### ISSUE TITLE
Failable init?

### ISSUE THREAD

**Issue by MoridinBG** [yeahdongcn/UIColor-Hex-Swift#21]
Any considerations to make the init method failable? Or provide an optional failable init?

It makes much more sense to me the init to be failable in case of an invalid string, as it allows for much better error handling than printing a message in the console.

**Comment by yeahdongcn** [comment]
I've done some changes on the master using guard to achieve better error handling, do you have time to review that?

**Comment by MoridinBG** [comment]
Cool, I will have a look
