### ISSUE TITLE
Dependency "UIColor-Hex-Swift" has no shared framework schemes

### ISSUE THREAD

**Issue by schjonhaug** [yeahdongcn/UIColor-Hex-Swift#23]
I'm using Carthage 0.9.3 and get this error when trying to use UIColor-Hex-Swift:

*** Checking out UIColor-Hex-Swift at "1.2"
*** Skipped building UIColor-Hex-Swift due to the error:
Dependency "UIColor-Hex-Swift" has no shared framework schemes

**Comment by yeahdongcn** [comment]
Could you try `github "yeahdongcn/UIColor-Hex-Swift" >= 1.3`?

**Comment by schjonhaug** [comment]
Yes, that worked. Thanks!
