### ISSUE TITLE
Minimum deployment target using Carthage

### ISSUE THREAD

**Issue by schjonhaug** [yeahdongcn/UIColor-Hex-Swift#24]
Using Carthage to install UIColor-Hex-Swift and my project's deployment target set to iOS 8.0, I get this error when building:

"Module file's minimum deployment target is ios9.0 v9.0"

Looking at the [pod spec](https://github.com/yeahdongcn/UIColor-Hex-Swift/blob/master/UIColor_Hex_Swift.podspec), it seems that the minimum version should be 8.0.

**Comment by yeahdongcn** [comment]
I will fix this soon.

**Comment by yeahdongcn** [comment]
Please try `github "yeahdongcn/UIColor-Hex-Swift" >= 1.3`

**Comment by schjonhaug** [comment]
Yes, now it works. Thanks.
