### ISSUE TITLE
Argument Labels Don't Match Overloads Issue

### ISSUE THREAD

**Issue by rinyfo4** [yeahdongcn/UIColor-Hex-Swift#27]
Hey, 

Great git guys. 

I followed the installation process and I get an error: 
        Argument labels '(rgba:)' do not match any available overloads')' when i try to add this line in my App Delegate 

        UITabBar.appearance().barTintColor = UIColor(rgba: "#12296f")

Do i have to add an import statement? If so what is it? What am i missing? 

Thanks a lot

**Comment by yeahdongcn** [comment]
import HEXColor

**Comment by Maxador** [comment]
Worked with
`import UIColor_Hex_Swift`

Using Cocoapods

**Comment by yeahdongcn** [comment]
Problem solved?
