### ISSUE TITLE
Change MinimumOSVersion to 8.0 to support Carthage builds

### ISSUE THREAD

**Issue by schjonhaug** [yeahdongcn/UIColor-Hex-Swift#28]
When trying to archive my project, I get the following error:

<img width="628" alt="skjermbilde 2015-12-04 kl 10 25 24" src="https://cloud.githubusercontent.com/assets/84225/11580588/e82a6e66-9a73-11e5-8436-cb214863a989.png">

This can be fixed by setting MinimumOSVersion to 8.0 in your Info.plist file.

**Comment by yeahdongcn** [comment]
Hi, just added the MinimumOSVersion, could you please try again?

**Comment by schjonhaug** [comment]
I still get the same error. This is the Info.plist that is found is Carthage/Build/iOS/HEXColor.framework

```
// !!! BINARY PROPERTY LIST WARNING !!!
//
// The pretty-printed property list below has been created
// from a binary version on disk and should not be saved as
// the ASCII format is a subset of the binary representation!
//
{	BuildMachineOSBuild = "15B42";
	CFBundleDevelopmentRegion = "en";
	CFBundleExecutable = "HEXColor";
	CFBundleIdentifier = "com.pdq.HEXColor";
	CFBundleInfoDictionaryVersion = "6.0";
	CFBundleName = "HEXColor";
	CFBundlePackageType = "FMWK";
	CFBundleShortVersionString = "1.0";
	CFBundleSignature = "????";
	CFBundleSupportedPlatforms = ( "iPhoneOS" );
	CFBundleVersion = "1";
	DTCompiler = "com.apple.compilers.llvm.clang.1_0";
	DTPlatformBuild = "13B137";
	DTPlatformName = "iphoneos";
	DTPlatformVersion = "9.1";
	DTSDKBuild = "13B137";
	DTSDKName = "iphoneos9.1";
	DTXcode = "0711";
	DTXcodeBuild = "7B1005";
	MinimumOSVersion = "7.0";
	UIDeviceFamily = ( 1, 2 );
}
```

**Comment by yeahdongcn** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>15B42</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>HEXColor</string>
	<key>CFBundleIdentifier</key>
	<string>com.pdq.HEXColor</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>HEXColor</string>
	<key>CFBundlePackageType</key>
	<string>FMWK</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>iPhoneOS</string>
	</array>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>13B137</string>
	<key>DTPlatformName</key>
	<string>iphoneos</string>
	<key>DTPlatformVersion</key>
	<string>9.1</string>
	<key>DTSDKBuild</key>
	<string>13B137</string>
	<key>DTSDKName</key>
	<string>iphoneos9.1</string>
	<key>DTXcode</key>
	<string>0711</string>
	<key>DTXcodeBuild</key>
	<string>7B1005</string>
	<key>MinimumOSVersion</key>
	<string>8.0</string>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>
</dict>
</plist>
