### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by phatmann** [yeahdongcn/UIColor-Hex-Swift#41]
Xcode 8 is out! Time to merge in Swift 3 branch.

**Comment by yeahdongcn** [comment]
This is one issue I met: http://stackoverflow.com/questions/39442664/open-override-var-description-string-not-called-in-swift-3, after I fix this I will do merge.

Could you help with this?

**Comment by phatmann** [comment]
Answer posted:

> You cannot override a method in an extension. You would need to use a subclass. The compiler should be complaining.
> 
> It might have worked in Swift 2.x, but that was not correct behavior.

Tony

**Comment by ynnckcmprnl** [comment]
Don't forget Swift 2.3 support. Some users won't be able to make the jump to Swift 3.0 immediately and will have to rely on a Swift 2.3 compatible version at first.

**Comment by yeahdongcn** [comment]
Done, Tag 2.3 for Swift 2.3, Tag 3.0 for Swift 3.0.
