### ISSUE TITLE
Developer From Android To iOS, #ARGB #AARRGGBB is Accepted better.

### ISSUE THREAD

**Issue by liuxue0905** [yeahdongcn/UIColor-Hex-Swift#42]
Color in Android is #AARRGGBB or #ARGB, So iOS developer trans from Android developer can accept that easier than #RRGGBBAA. May be Support it, UIColor-Hex-Swift will be populer than befor.

**Comment by yeahdongcn** [comment]
Please see: https://github.com/yeahdongcn/UIColor-Hex-Swift/releases/tag/3.0.2
