### ISSUE TITLE
Ambiguous use of init(_:defaultColor:)

### ISSUE THREAD

**Issue by sicaboy** [yeahdongcn/UIColor-Hex-Swift#43]
<img width="1130" alt="screen shot 2016-10-31 at 4 51 39 pm" src="https://cloud.githubusercontent.com/assets/2426114/19845374/646f38dc-9f8a-11e6-8731-bb297ef68184.png">

Does anyone have ideas about how to solve it? 

XCode 8.1
Swift 3.0

**Comment by yeahdongcn** [comment]
<img width="647" alt="1" src="https://cloud.githubusercontent.com/assets/2831050/19855677/cee71614-9fb0-11e6-8fef-731a71b3134c.png">
![2](https://cloud.githubusercontent.com/assets/2831050/19855678/cf2554e2-9fb0-11e6-8c4c-5f31c9987e08.png)
