### ISSUE TITLE
Some people always get used to the 0.0~1.0 way alpha. Will you support?

### ISSUE THREAD

**Issue by weichencoder** [yeahdongcn/UIColor-Hex-Swift#44]

**Comment by yeahdongcn** [comment]
Could you explain a little bit more? 写中文好了

**Comment by weichencoder** [comment]
就是说：好像人们一般习惯色值采用#FFFFFF这种。都是透明度不习惯用#FF这种。而是习惯0.5这样的比较直观的数字。。你就说吧，透明度0.5转换为#XX格式的十六进制的是多少？你能想明白吗？

**Comment by yeahdongcn** [comment]
已经提供了带alpha的convenience init

    public convenience init(hex3: UInt16, alpha: CGFloat = 1) 
    public convenience init(hex6: UInt32, alpha: CGFloat = 1)
