### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by xPutnikx** [yeahdongcn/UIColor-Hex-Swift#45]
Tried to build the app on Swift 3.0, XCode version 8.2.1
I got the error on linking step.

Undefined symbols for architecture x86_64:
  "(extension in UIColor_Hex_Swift):__ObjC.UIColor.(init (Swift.String, defaultColor : __ObjC.UIColor) -> __ObjC.UIColor).(default argument 1)"

**Comment by yeahdongcn** [comment]
I got nothing useful, could you provide your code?

**Comment by xPutnikx** [comment]
I sure my code will not help you too
`
import UIColor_Hex_Swift
extension UIColor {    
    class var darkButtonNormal: UIColor {
        return UIColor("#260A38")
    }
}
`

**Comment by yeahdongcn** [comment]
Is your problem resolved?
