### ISSUE TITLE
Argument labels '(rgba:)' do not match any available overloads

### ISSUE THREAD

**Issue by googlb** [yeahdongcn/UIColor-Hex-Swift#46]
pod 'UIColor_Hex_Swift', '~> 3.0.2'
import UIColor_Hex_Swift

Argument labels '(rgba:)' do not match any available overloads

import HEXColor no such model

**Comment by yeahdongcn** [comment]
import HEXColor

UIColor("#FFFFFFFF")

**Comment by googlb** [comment]
import HEXColor 
xcode point no such model 'HEXColor'

**Comment by yeahdongcn** [comment]
Could you share me your project I may found the problem?

**Comment by googlb** [comment]
Before I convert the project from Swift 2.3 to Swift 3. import UIColor_Hex_Swift is worked.But after converted and update UIColor_Hex_Swift version to 3.0.2,it build error:
Argument labels '(rgba:)' do not match any available overloads
I found the same problem[issues/27](https://github.com/yeahdongcn/UIColor-Hex-Swift/issues/27)
I try import HEXColor but I get error 'no such model HEXColor',In additon to HEXColor ,what i missed？

**Comment by googlb** [comment]
You can find the problem on this demo [HEXColorDemo](https://github.com/googlb/HEXColorDemo.git)

**Comment by yeahdongcn** [comment]
OK, I'll look into this tonight.

**Comment by yeahdongcn** [comment]
Import UIColor_Hex_Swift instead of HEXColor

**Comment by ramirez** [comment]
I have the exact same problem. After converting my project to Swift 3.0, I get `Argument labels '(rgba:)' do not match any available overloads`.  I'm using `Import UIColor_Hex_Swift` instead of `HEXColor` but it just does not work.
