### ISSUE TITLE
Invalid hex strings produced from wide display colors

### ISSUE THREAD

**Issue by jordansmithnz** [yeahdongcn/UIColor-Hex-Swift#51]
The documentation for getRed(_: green: blue: ) explains that older versions of iOS always set the values to a range within 0 and 1, but not any more. When one of these returns outside the expected range, hexString(_:) produces invalid hex codes (for example, #54A8FFFFFFDF).

**Comment by yeahdongcn** [comment]
Can you provide some code to show the error? Thanks.

**Comment by jordansmithnz** [comment]
Sure, like so:

`UIColor.init(red: 0.5, green: -0.1, blue: -0.1, alpha:1).hexString(false)`

In practice most use probably probably aren't manually creating wide colors, but if you've got an algorithm generating colors from a wide color image, or perhaps converting between color spaces (which was my issue) then you could run into this. 

I don't think you can really represent the wide color properly in hex, but clamping the values to between zero and one before conversion would probably give the closest hex representable color.

**Comment by yeahdongcn** [comment]
Do you mean

`func n(v: CGFloat) -> CGFloat {
      if v < 0 {
         return 0
      } else if v > 1 {
         return 1
      }
      return v
   }

      r = self.n(v: r)
      g = self.n(v: g)
      b = self.n(v: b)`

How about throwing an error?

**Comment by jordansmithnz** [comment]
Yeah, that's pretty similar to what I've done. The main reason I haven't submitted a pull request is because the right solution isn't very obvious.

It wouldn't be 100% 'correct' to label a wide color with a hex code, so throwing an error would be more accurate. That introduces a throw into the function though, which is a breaking change (and isn't all that nice for something so commonly used). Perhaps making the result optional would be best?

Then there's also the chance that others running into the issue would just want the closest hex color anyway. Perhaps another parameter, `stripWideColor: Bool = true` would be helpful, and make library users aware of the possible nil case?

**Comment by yeahdongcn** [comment]
Sure, your suggestion looks great. I will consider how to update this, thank you.

**Comment by yeahdongcn** [comment]
60500b0c51778092302235a1e1ccf525f4266822
