### ISSUE TITLE
'substring(from:)' is deprecated in Swift 4

### ISSUE THREAD

**Issue by JEKos** [yeahdongcn/UIColor-Hex-Swift#52]
Hi, in Swift 4, your library says `'substring(from:)' is deprecated: Please use String slicing subscript with a 'partial range from' operator.` in too many places. Can you fix it?

**Comment by Ngugi1** [comment]
I am having the same issue here

**Comment by yeahdongcn** [comment]
I merged @Eunryu's PR and it should be worked now. Thanks.
