### ISSUE TITLE
version 4.0.0 it's not yet on cocoapods

### ISSUE THREAD

**Issue by JEKos** [yeahdongcn/UIColor-Hex-Swift#55]
Hi,
When I try `pod 'UIColor_Hex_Swift', '~> 4.0.0'` it cause error on `pod update`. It seems version 4 it's not updated on cocoapods yet. 
I used `pod 'UIColor_Hex_Swift', :git => 'https://github.com/yeahdongcn/UIColor-Hex-Swift.git'` and it works

**Comment by yeahdongcn** [comment]
That's my fault, sorry about that. I was unable to push the 4.0.0 to cocoapods, there are some validation errors I haven't seen before. I will try again after 10/10.

**Comment by francoisduchemin** [comment]
I have the same issue... were you able to push 4.0.0 to cocoapods?

**Comment by yeahdongcn** [comment]
I was still unable to push the spec to cocoapods...
Could you please try just use the master branch?

**Comment by francoisduchemin** [comment]
Yep master is working fine, thanks.

**Comment by sghiassy** [comment]
`4.0.0` is still not on Cocoapods. In case it helps, the commands are

```bash
pod lib lint --swift-version=4 --verbose --no-clean  #verify all is good. If it breaks the Xcode project will be logged and you can visit the file on your HD
git tag 4.0.0 # tag the SHA that is working noe
git push --tags # push tag to origin
pod trunk push UIColor_Hex_Swift.podspec # publish
```

**Comment by electic** [comment]
Would be great if someone could push this out:)

**Comment by yeahdongcn** [comment]
After switching to a new computer, I was finally able to push the pod spec. Please use 4.0.1, thanks.
