### ISSUE TITLE
Use methods in objective c class in swift 4 project

### ISSUE THREAD

**Issue by Athenay** [yeahdongcn/UIColor-Hex-Swift#59]
Hi,
I have an objective-c class in swift 4 based project, I wanted to use this method, After successfully importing you pod in my objC class, methods had not been recognized.
I unlocked the UIColorExtension.swift and added @objc tag to your extension so i could use its method in my class

would you add this tag to your class for compatible it by objetive c classes ? 

thanks

**Comment by yeahdongcn** [comment]
Please see 286b10a8a4a345d6350e978961e64eab33024943
