### ISSUE TITLE
No such module 'UIColor_Hex_Swift'

### ISSUE THREAD

**Issue by Allan-Nava** [yeahdongcn/UIColor-Hex-Swift#62]
`No such module 'UIColor_Hex_Swift'`
How can i fix this problem?

<img width="266" alt="schermata 2018-02-08 alle 22 52 38" src="https://user-images.githubusercontent.com/22498435/36000317-d2e0f5ec-0d22-11e8-8d38-ee3fbf16bb19.png">

<img width="703" alt="schermata 2018-02-08 alle 22 53 27" src="https://user-images.githubusercontent.com/22498435/36000354-ef2f5cac-0d22-11e8-89ee-8b6f4a31e4f3.png">

**Comment by SeRG1k17** [comment]
@Allan-Nava try clean project and build again.

**Comment by Allan-Nava** [comment]
I have tried a lot of time but I have the same error @SeRG1k17

**Comment by yeahdongcn** [comment]
Is your problem resolved? @Allan-Nava

**Comment by Allan-Nava** [comment]
Hi @yeahdongcn , no I also install with brew but It doesn't work

**Comment by yeahdongcn** [comment]
Could you please send me your sample project through the email?

**Comment by Allan-Nava** [comment]
Ok @yeahdongcn -> https://github.com/Allan-Nava/HelloWorldSwift

**Comment by yeahdongcn** [comment]
Could you please try "pod 'UIColor_Hex_Swift', '~> 4.0.1'" in your pod file?

**Comment by Allan-Nava** [comment]
Ok, how can I fix?


2018-02-22 8:21 GMT+01:00 R0CKSTAR <notifications@github.com>:

**Comment by yeahdongcn** [comment]
You need to examine your Podfile to make sure you have to the right version for your project.

**Comment by Allan-Nava** [comment]
I have change my pod file:
<img width="1440" alt="schermata 2018-02-22 alle 08 33 17" src="https://user-images.githubusercontent.com/22498435/36525592-0e823ed4-17ab-11e8-9453-b7ff950ba387.png">


This is my new project and I add in frameworks:
<img width="1440" alt="schermata 2018-02-22 alle 08 32 14" src="https://user-images.githubusercontent.com/22498435/36525607-1bedc50c-17ab-11e8-810b-63715b47b845.png">
<img width="1440" alt="schermata 2018-02-22 alle 08 32 09" src="https://user-images.githubusercontent.com/22498435/36525609-1c0d8950-17ab-11e8-892d-aee27594bc68.png">

**Comment by Slavi-Slavchev** [comment]
i have same problem, any ideas?

**Comment by bigtotorouk** [comment]
same problem. how to fix it

**Comment by jackylcs86** [comment]
Same problem. Still how to fix it?

**Comment by Allan-Nava** [comment]
Me too
