### ISSUE TITLE
UIColor convert to hex problem!!

### ISSUE THREAD

**Issue by phpmaple** [yeahdongcn/UIColor-Hex-Swift#65]
```
public func hexString(_ includeAlpha: Bool) -> String {
        var r: CGFloat = 0
        var g: CGFloat = 0
        var b: CGFloat = 0
        var a: CGFloat = 0
        self.getRed(&r, green: &g, blue: &b, alpha: &a)
        
        if (includeAlpha) {
            return String(format: "#%02X%02X%02X%02X", Int(r * 255), Int(g * 255), Int(b * 255), Int(a * 255))
        } else {
            return String(format: "#%02X%02X%02X", Int(r * 255), Int(g * 255), Int(b * 255))
        }
    }
```

`return String(format: "#%02X%02X%02X%02X", Int(r * 255), Int(g * 255), Int(b * 255), Int(a * 255))`

this line should be

`return String(format: "#%02X%02X%02X%02X", Int(round(r * 255)), Int(round(g * 255)), Int(round(b * 255)), Int(round(a * 255)))`

if don't round, after convert to hex, hex to UIColor could loss of precision

example rgb 27 34 48, after it will be 27 33 47

**Comment by yeahdongcn** [comment]
A PR is appreciated.

**Comment by yeahdongcn** [comment]
e3ab0c2e6e3fc864cb1565b74516e068b268a964
