### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by tradingstratagem** [yeahdongcn/UIColor-Hex-Swift#71]
I see that the support for SPM has been added, when you will release a new version in order to be able to add the package to SPM?

Now I have the following error:
<img width="557" alt="Screenshot 2019-10-05 at 17 14 47" src="https://user-images.githubusercontent.com/38089167/66256954-a4a50e00-e793-11e9-8178-5da977c0ac97.png">

**Comment by yeahdongcn** [comment]
I pushed a new tag 5.1.1, this issue should be fixed.

**Comment by tradingstratagem** [comment]
Yes, thx!
