### ISSUE TITLE
This bundle is invalid

### ISSUE THREAD

**Issue by jgarrick1992** [yeahdongcn/UIColor-Hex-Swift#76]
TMS-90049: This bundle is invalid - The bundle at path Payload/***.app/Frameworks/UIColor_Hex_Swift.framework has an invalid CFBundleIdentifier 'UIColor_Hex_Swift' There are invalid characters(characters that are not dots, hyphen and alphanumerics) that have been replaced with their code point 'UIColor\u005fHex\u005fSwift' CFBundleIdentifier must be present, must contain only alphanumerics, dots, hyphens and must not end with a dot. [see the Core Foundation Keys at

'UIColor_Hex_Swift', '~> 5.1.6'

**Comment by yeahdongcn** [comment]
Should be resolved by https://github.com/yeahdongcn/UIColor-Hex-Swift/pull/75
