### ISSUE TITLE
Can't find package with Xcode 13.1

### ISSUE THREAD

**Issue by garageshop** [yeahdongcn/UIColor-Hex-Swift#79]
Hi,

Thanks for offering a great package.

Swift Package Manager can no longer find UIColor-Hex-Swift after updating to the latest version of Xcode. 

Any idea why?

Thanks!
Blessings,
--Mark

**Comment by yeahdongcn** [comment]
I don't know for sure whether this is an Xcode problem, but I just tried to search packages like https://github.com/ReactiveX/RxSwift.git, Xcode displays the loading indicator all the time.
To work around this, you could clone the repo and choose "Add Local..." then select the clone path of UIColor-Hex-Swift.

**Comment by garageshop** [comment]
Thanks so much, I will give that a try.
